import {
  c_content_Color,
  c_button_m_primary__icon_Color,
  c_button_m_primary_Color,
  c_button_m_primary_hover_Color,
  c_button_m_primary_m_clicked_Color,
  c_button_m_primary_BackgroundColor,
  c_button_m_primary_hover_BackgroundColor,
  c_button_m_primary_m_clicked_BackgroundColor,
  t_global_border_color_status_danger_default,
  t_global_border_color_status_danger_clicked,
  t_global_border_color_status_danger_hover,
  t_global_background_color_secondary_default,
  t_global_background_color_primary_default,
  c_button_m_tertiary__icon_Color,
  c_button_m_tertiary_Color,
  c_button_m_tertiary_hover_Color,
  c_button_m_tertiary_m_clicked_Color,
  t_global_background_color_floating_default,
  t_global_border_color_status_warning_default,
  t_global_color_status_warning_default,
  t_global_text_color_regular,
  c_button_m_tertiary_BorderColor,
  c_button_m_tertiary_hover_BorderColor,
  c_button_m_tertiary_m_clicked_BorderColor,
  t_global_border_color_default,
} from '@patternfly/react-tokens';
import pfTokens from 'mod-arch-kubeflow/dist/style/pf-tokens-SSOT.json';

export const colorList: Record<string, string> = {
  actionPrimaryBackgroundDefault: pfTokens.components.button[c_button_m_primary_BackgroundColor.name],
  actionPrimaryBackgroundHover: pfTokens.components.button[c_button_m_primary_hover_BackgroundColor.name],
  actionPrimaryBackgroundPress: pfTokens.components.button[c_button_m_primary_m_clicked_BackgroundColor.name],
  actionPrimaryTextDefault: pfTokens.components.button[c_button_m_primary_Color.name],
  actionPrimaryTextHover: pfTokens.components.button[c_button_m_primary_hover_Color.name],
  actionPrimaryTextPress: pfTokens.components.button[c_button_m_primary_m_clicked_Color.name],
  actionPrimaryIcon: pfTokens.components.button[c_button_m_primary__icon_Color.name],

  actionDefaultBorderDefault: t_global_border_color_default.var,
  actionDefaultBorderFocus: pfTokens.components.button[c_button_m_primary_BackgroundColor.name],
  actionDefaultBorderHover: pfTokens.components.button[c_button_m_primary_BackgroundColor.name],
  actionDefaultBorderPress: pfTokens.components.button[c_button_m_primary_m_clicked_BackgroundColor.name],
  actionDefaultIconDefault: c_content_Color.var,
  actionDefaultIconHover: pfTokens.components.button[c_button_m_primary_hover_Color.name],
  actionDefaultIconPress: pfTokens.components.button[c_button_m_primary_m_clicked_Color.name],

  actionIconBackgroundDefault: pfTokens.components.button[c_button_m_primary_BackgroundColor.name],
  actionIconBackgroundHover: pfTokens.components.button[c_button_m_primary_hover_BackgroundColor.name],
  actionIconBackgroundPress: pfTokens.components.button[c_button_m_primary_m_clicked_BackgroundColor.name],
  actionIconIconDefault: c_content_Color.var,
  actionIconIconHover: pfTokens.components.button[c_button_m_primary_hover_Color.name],
  actionIconIconPress: pfTokens.components.button[c_button_m_primary_m_clicked_Color.name],

  actionTertiaryBackgroundDefault: t_global_background_color_floating_default.var,
  actionTertiaryBackgroundHover: t_global_background_color_floating_default.var,
  actionTertiaryBackgroundPress: t_global_background_color_floating_default.var,
  actionTertiaryBorderDefault: pfTokens.components.button[c_button_m_tertiary_BorderColor.name],
  actionTertiaryBorderHover: pfTokens.components.button[c_button_m_tertiary_hover_BorderColor.name],
  actionTertiaryBorderPress: pfTokens.components.button[c_button_m_tertiary_m_clicked_BorderColor.name],
  actionTertiaryTextDefault: pfTokens.components.button[c_button_m_tertiary_Color.name],
  actionTertiaryIconDefault: pfTokens.components.button[c_button_m_tertiary__icon_Color.name],
  actionTertiaryIconHover: pfTokens.components.button[c_button_m_tertiary_hover_Color.name],
  actionTertiaryIconPress: pfTokens.components.button[c_button_m_tertiary_m_clicked_Color.name],
  actionTertiaryTextHover: pfTokens.components.button[c_button_m_tertiary_hover_Color.name],
  actionTertiaryTextPress: pfTokens.components.button[c_button_m_tertiary_m_clicked_Color.name],

  actionDangerDefaultBackgroundDefault: t_global_background_color_floating_default.var,
  actionDangerDefaultBackgroundHover: t_global_background_color_floating_default.var,
  actionDangerDefaultBackgroundPress: t_global_background_color_floating_default.var,
  actionDangerDefaultBorderDefault: t_global_border_color_status_danger_default.var,
  actionDangerDefaultBorderHover: t_global_border_color_status_danger_hover.var,
  actionDangerDefaultBorderPress: t_global_border_color_status_danger_clicked.var,
  actionDangerDefaultTextDefault: t_global_text_color_regular.var,
  actionDangerDefaultTextHover: t_global_text_color_regular.var,
  actionDangerDefaultTextPress: t_global_text_color_regular.var,
  actionDangerPrimaryBackgroundDefault: t_global_background_color_floating_default.var,
  actionDangerPrimaryBackgroundHover: t_global_background_color_floating_default.var,
  actionDangerPrimaryBackgroundPress: t_global_background_color_floating_default.var,
  actionDangerPrimaryText: t_global_background_color_primary_default.var,

  backgroundDanger: t_global_background_color_floating_default.var,
  backgroundPrimary: t_global_background_color_primary_default.var,
  backgroundSecondary: t_global_background_color_secondary_default.var,
  backgroundSuccess: t_global_background_color_floating_default.var,
  backgroundWarning: t_global_color_status_warning_default.var,

  border: t_global_border_color_default.var,
  borderAccessible: c_content_Color.var,
  borderDanger: t_global_border_color_status_danger_default.var,
  borderWarning: t_global_border_color_status_warning_default.var,

  textPlaceholder: c_content_Color.var,
  textPrimary: c_content_Color.var,
  textSecondary: c_content_Color.var,
  textValidationDanger: t_global_text_color_regular.var,
  textValidationSuccess: t_global_text_color_regular.var,
  textValidationWarning: t_global_text_color_regular.var,
};
