"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Proto definition for MLflow OSS-native label schemas.
Schemas are experiment-scoped UI rendering hints that drive the
reviewer-facing widgets in the labeling UI. They do not gate or validate assessment
writes; the entity is intentionally lightweight and the schema_id is
soft-referenced from assessments.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _LabelSchemaType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LabelSchemaTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LabelSchemaType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LABEL_SCHEMA_TYPE_UNSPECIFIED: _LabelSchemaType.ValueType  # 0
    FEEDBACK: _LabelSchemaType.ValueType  # 1
    """Feedback schema: bounded value space (pass/fail, options, min/max)."""
    EXPECTATION: _LabelSchemaType.ValueType  # 2
    """Expectation schema: typically ground-truth labels supplied by reviewers."""

class LabelSchemaType(_LabelSchemaType, metaclass=_LabelSchemaTypeEnumTypeWrapper):
    """Type of label schema. Mirrors mlflow.genai.label_schemas.LabelSchemaType.
    The zero-value `LABEL_SCHEMA_TYPE_UNSPECIFIED` is a defensive sentinel;
    the handler must reject it explicitly because `validate_required` on a
    proto2 optional enum only enforces HasField, not value validity, so a
    client can pass UNSPECIFIED past the wire-level required check.
    """

LABEL_SCHEMA_TYPE_UNSPECIFIED: LabelSchemaType.ValueType  # 0
FEEDBACK: LabelSchemaType.ValueType  # 1
"""Feedback schema: bounded value space (pass/fail, options, min/max)."""
EXPECTATION: LabelSchemaType.ValueType  # 2
"""Expectation schema: typically ground-truth labels supplied by reviewers."""
Global___LabelSchemaType: _TypeAlias = LabelSchemaType  # noqa: Y015

@_typing.final
class InputPassFail(_message.Message):
    """Pass/Fail input rendered as a thumbs-up / thumbs-down toggle.
    OSS-only; Databricks-routed schemas should use InputCategorical instead.
    """

    DESCRIPTOR: _descriptor.Descriptor

    POSITIVE_LABEL_FIELD_NUMBER: _builtins.int
    NEGATIVE_LABEL_FIELD_NUMBER: _builtins.int
    positive_label: _builtins.str
    """Label shown next to the thumbs-up button (e.g., "Correct", "Pass")."""
    negative_label: _builtins.str
    """Label shown next to the thumbs-down button (e.g., "Incorrect", "Fail")."""
    def __init__(
        self,
        *,
        positive_label: _builtins.str | None = ...,
        negative_label: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["negative_label", b"negative_label", "positive_label", b"positive_label"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["negative_label", b"negative_label", "positive_label", b"positive_label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InputPassFail: _TypeAlias = InputPassFail  # noqa: Y015

@_typing.final
class InputCategorical(_message.Message):
    """Categorical (single- or multi-select) input. Option ordering is
    author-controlled, so there is no separate polarity hint.
    """

    DESCRIPTOR: _descriptor.Descriptor

    OPTIONS_FIELD_NUMBER: _builtins.int
    MULTI_SELECT_FIELD_NUMBER: _builtins.int
    multi_select: _builtins.bool
    """When true, the widget renders multi-select and the assessment value
    becomes a list of strings. Defaults to false (single-select).
    """
    @_builtins.property
    def options(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The available options."""

    def __init__(
        self,
        *,
        options: _abc.Iterable[_builtins.str] | None = ...,
        multi_select: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["multi_select", b"multi_select"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["multi_select", b"multi_select", "options", b"options"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InputCategorical: _TypeAlias = InputCategorical  # noqa: Y015

@_typing.final
class InputNumeric(_message.Message):
    """Numeric input bounded by min_value / max_value. Both bounds are
    optional regardless of schema type.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MIN_VALUE_FIELD_NUMBER: _builtins.int
    MAX_VALUE_FIELD_NUMBER: _builtins.int
    min_value: _builtins.float
    max_value: _builtins.float
    def __init__(
        self,
        *,
        min_value: _builtins.float | None = ...,
        max_value: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["max_value", b"max_value", "min_value", b"min_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_value", b"max_value", "min_value", b"min_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InputNumeric: _TypeAlias = InputNumeric  # noqa: Y015

@_typing.final
class InputText(_message.Message):
    """Free-form text input. Supported for both feedback and expectation
    schemas (e.g., free-form rationale or ground-truth text).
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAX_LENGTH_FIELD_NUMBER: _builtins.int
    max_length: _builtins.int
    """Maximum character length. Unset means no limit."""
    def __init__(
        self,
        *,
        max_length: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["max_length", b"max_length"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_length", b"max_length"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InputText: _TypeAlias = InputText  # noqa: Y015

@_typing.final
class LabelSchemaInput(_message.Message):
    """Discriminated input wrapper. Exactly one input type is set per schema.

    NOTE on `validate_required`: when a request message uses
    `LabelSchemaInput input = N [(validate_required) = true]`, the wire-level
    check only verifies that the wrapper message is set. It does NOT enforce
    that any oneof variant inside the wrapper is set, so a client can send
    `{"input": {}}` and pass validation. Handlers must additionally check
    `request.input.WhichOneof("input") is not None`.

    Tags 1-3 and 5 cover the OSS-supported input types. Tags 4 and 6 are
    reserved for the Databricks-only input variants (InputCategoricalList,
    InputTextList) in case hybrid scenarios ever need to round-trip them
    through this proto; do not reuse these tags for new OSS variants.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PASS_FAIL_FIELD_NUMBER: _builtins.int
    CATEGORICAL_FIELD_NUMBER: _builtins.int
    NUMERIC_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pass_fail(self) -> Global___InputPassFail: ...
    @_builtins.property
    def categorical(self) -> Global___InputCategorical: ...
    @_builtins.property
    def numeric(self) -> Global___InputNumeric: ...
    @_builtins.property
    def text(self) -> Global___InputText: ...
    def __init__(
        self,
        *,
        pass_fail: Global___InputPassFail | None = ...,
        categorical: Global___InputCategorical | None = ...,
        numeric: Global___InputNumeric | None = ...,
        text: Global___InputText | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["categorical", b"categorical", "input", b"input", "numeric", b"numeric", "pass_fail", b"pass_fail", "text", b"text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["categorical", b"categorical", "input", b"input", "numeric", b"numeric", "pass_fail", b"pass_fail", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_input: _TypeAlias = _typing.Literal["pass_fail", "categorical", "numeric", "text"]  # noqa: Y015
    _WhichOneofArgType_input: _TypeAlias = _typing.Literal["input", b"input"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_input) -> _WhichOneofReturnType_input | None: ...

Global___LabelSchemaInput: _TypeAlias = LabelSchemaInput  # noqa: Y015

@_typing.final
class LabelSchema(_message.Message):
    """Full label schema entity."""

    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    INSTRUCTION_FIELD_NUMBER: _builtins.int
    ENABLE_COMMENT_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    CREATED_BY_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    LAST_UPDATED_AT_FIELD_NUMBER: _builtins.int
    IS_DEFAULT_FIELD_NUMBER: _builtins.int
    schema_id: _builtins.str
    """Server-generated identifier."""
    experiment_id: _builtins.str
    """Parent experiment ID."""
    name: _builtins.str
    """Schema name (1-256 chars; unique within experiment). Free text shown
    to reviewers as the label prompt and used as the assessment key.
    """
    type: Global___LabelSchemaType.ValueType
    instruction: _builtins.str
    """Optional supplementary guidance, <=1000 chars."""
    enable_comment: _builtins.bool
    """UI hint: whether the widget renders a free-form comment input."""
    created_by: _builtins.str
    """User who created the schema (OSS-native)."""
    created_at: _builtins.int
    """Creation timestamp in milliseconds since epoch."""
    last_updated_at: _builtins.int
    """Last update timestamp in milliseconds since epoch."""
    is_default: _builtins.bool
    """Whether this is the experiment's protected default question: server-seeded,
    undeletable, and uneditable. Read-only to clients.
    """
    @_builtins.property
    def input(self) -> Global___LabelSchemaInput: ...
    def __init__(
        self,
        *,
        schema_id: _builtins.str | None = ...,
        experiment_id: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
        type: Global___LabelSchemaType.ValueType | None = ...,
        instruction: _builtins.str | None = ...,
        enable_comment: _builtins.bool | None = ...,
        input: Global___LabelSchemaInput | None = ...,
        created_by: _builtins.str | None = ...,
        created_at: _builtins.int | None = ...,
        last_updated_at: _builtins.int | None = ...,
        is_default: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "created_by", b"created_by", "enable_comment", b"enable_comment", "experiment_id", b"experiment_id", "input", b"input", "instruction", b"instruction", "is_default", b"is_default", "last_updated_at", b"last_updated_at", "name", b"name", "schema_id", b"schema_id", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "created_by", b"created_by", "enable_comment", b"enable_comment", "experiment_id", b"experiment_id", "input", b"input", "instruction", b"instruction", "is_default", b"is_default", "last_updated_at", b"last_updated_at", "name", b"name", "schema_id", b"schema_id", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LabelSchema: _TypeAlias = LabelSchema  # noqa: Y015

@_typing.final
class CreateLabelSchema(_message.Message):
    """Request to create a new label schema."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Response(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_SCHEMA_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label_schema(self) -> Global___LabelSchema: ...
        def __init__(
            self,
            *,
            label_schema: Global___LabelSchema | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    INSTRUCTION_FIELD_NUMBER: _builtins.int
    ENABLE_COMMENT_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    name: _builtins.str
    type: Global___LabelSchemaType.ValueType
    instruction: _builtins.str
    enable_comment: _builtins.bool
    @_builtins.property
    def input(self) -> Global___LabelSchemaInput: ...
    def __init__(
        self,
        *,
        experiment_id: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
        type: Global___LabelSchemaType.ValueType | None = ...,
        input: Global___LabelSchemaInput | None = ...,
        instruction: _builtins.str | None = ...,
        enable_comment: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["enable_comment", b"enable_comment", "experiment_id", b"experiment_id", "input", b"input", "instruction", b"instruction", "name", b"name", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enable_comment", b"enable_comment", "experiment_id", b"experiment_id", "input", b"input", "instruction", b"instruction", "name", b"name", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateLabelSchema: _TypeAlias = CreateLabelSchema  # noqa: Y015

@_typing.final
class GetLabelSchema(_message.Message):
    """Request to get a label schema by ID. `schema_id` is the OSS-only
    canonical primary key; Databricks-routed schemas (whose canonical
    identity is `(review_app_id, name)`) do not round-trip through this
    RPC. Use GetLabelSchemaByName for the (experiment_id, name) lookup.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Response(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_SCHEMA_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label_schema(self) -> Global___LabelSchema: ...
        def __init__(
            self,
            *,
            label_schema: Global___LabelSchema | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    schema_id: _builtins.str
    def __init__(
        self,
        *,
        schema_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema_id", b"schema_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema_id", b"schema_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetLabelSchema: _TypeAlias = GetLabelSchema  # noqa: Y015

@_typing.final
class GetLabelSchemaByName(_message.Message):
    """Request to get a label schema by (experiment_id, name)."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Response(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_SCHEMA_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label_schema(self) -> Global___LabelSchema: ...
        def __init__(
            self,
            *,
            label_schema: Global___LabelSchema | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    name: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetLabelSchemaByName: _TypeAlias = GetLabelSchemaByName  # noqa: Y015

@_typing.final
class ListLabelSchemas(_message.Message):
    """Request to list label schemas for an experiment, paginated."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Response(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_SCHEMAS_FIELD_NUMBER: _builtins.int
        NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
        next_page_token: _builtins.str
        @_builtins.property
        def label_schemas(self) -> _containers.RepeatedCompositeFieldContainer[Global___LabelSchema]: ...
        def __init__(
            self,
            *,
            label_schemas: _abc.Iterable[Global___LabelSchema] | None = ...,
            next_page_token: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label_schemas", b"label_schemas", "next_page_token", b"next_page_token"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    MAX_RESULTS_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    max_results: _builtins.int
    """Defaults to 100 server-side when unset. Must be a positive integer
    not exceeding SEARCH_MAX_RESULTS_THRESHOLD; the handler rejects 0,
    negative values, and values above the threshold.
    """
    page_token: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str | None = ...,
        max_results: _builtins.int | None = ...,
        page_token: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id", "max_results", b"max_results", "page_token", b"page_token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id", "max_results", b"max_results", "page_token", b"page_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListLabelSchemas: _TypeAlias = ListLabelSchemas  # noqa: Y015

@_typing.final
class UpdateLabelSchema(_message.Message):
    """Request to sparse-update an existing label schema. `type` is immutable
    and is intentionally omitted from this message. The handler treats an
    absent field (HasField=false) as "unchanged" and a set field as the new
    value; an empty string written for `instruction` will replace the
    stored value with the empty string rather than clearing it.

    `name` may be renamed; existing assessment rows are NOT migrated (their
    `name` continues to reference the prior schema name), matching the
    store-layer contract documented on AbstractStore.update_label_schema.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Response(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LABEL_SCHEMA_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def label_schema(self) -> Global___LabelSchema: ...
        def __init__(
            self,
            *,
            label_schema: Global___LabelSchema | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["label_schema", b"label_schema"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    INSTRUCTION_FIELD_NUMBER: _builtins.int
    ENABLE_COMMENT_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    schema_id: _builtins.str
    name: _builtins.str
    instruction: _builtins.str
    enable_comment: _builtins.bool
    @_builtins.property
    def input(self) -> Global___LabelSchemaInput: ...
    def __init__(
        self,
        *,
        schema_id: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
        instruction: _builtins.str | None = ...,
        enable_comment: _builtins.bool | None = ...,
        input: Global___LabelSchemaInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["enable_comment", b"enable_comment", "input", b"input", "instruction", b"instruction", "name", b"name", "schema_id", b"schema_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enable_comment", b"enable_comment", "input", b"input", "instruction", b"instruction", "name", b"name", "schema_id", b"schema_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateLabelSchema: _TypeAlias = UpdateLabelSchema  # noqa: Y015

@_typing.final
class DeleteLabelSchema(_message.Message):
    """Request to delete a label schema. No-op when the schema doesn't exist."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Response(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SCHEMA_ID_FIELD_NUMBER: _builtins.int
    schema_id: _builtins.str
    def __init__(
        self,
        *,
        schema_id: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema_id", b"schema_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema_id", b"schema_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteLabelSchema: _TypeAlias = DeleteLabelSchema  # noqa: Y015
