package main

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/mlflow/mlflow/mlflow/go/tools/generate/discovery"
)

func mkImportSpec(value string) *ast.ImportSpec {
	return &ast.ImportSpec{Path: &ast.BasicLit{Kind: token.STRING, Value: value}}
}

var importStatements = &ast.GenDecl{
	Tok: token.IMPORT,
	Specs: []ast.Spec{
		mkImportSpec(`"github.com/gofiber/fiber/v2"`),
		mkImportSpec(`"github.com/mlflow/mlflow/mlflow/go/pkg/protos"`),
	},
}

func mkStarExpr(e ast.Expr) *ast.StarExpr {
	return &ast.StarExpr{
		X: e,
	}
}

func mkSelectorExpr(x, sel string) *ast.SelectorExpr {
	return &ast.SelectorExpr{X: ast.NewIdent(x), Sel: ast.NewIdent(sel)}
}

func mkNamedField(name string, typ ast.Expr) *ast.Field {
	return &ast.Field{
		Names: []*ast.Ident{ast.NewIdent(name)},
		Type:  typ,
	}
}

func mkField(typ ast.Expr) *ast.Field {
	return &ast.Field{
		Type: typ,
	}
}

func mkMethodInfoInputPointerType(methodInfo discovery.MethodInfo) *ast.StarExpr {
	return mkStarExpr(mkSelectorExpr(methodInfo.PackageName, methodInfo.Input))
}

// Generate a method declaration on an service interface.
func mkServiceInterfaceMethod(methodInfo discovery.MethodInfo) *ast.Field {
	return &ast.Field{
		Names: []*ast.Ident{ast.NewIdent(strcase.ToCamel(methodInfo.Name))},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("input", mkMethodInfoInputPointerType(methodInfo)),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					mkField(mkStarExpr(mkSelectorExpr(methodInfo.PackageName, methodInfo.Output))),
					mkField(mkStarExpr(ast.NewIdent("Error"))),
				},
			},
		},
	}
}

// Generate a service interface declaration.
func mkServiceInterfaceNode(serviceInfo discovery.ServiceInfo) *ast.GenDecl {
	// We add one method to validate any of the input structs
	methods := make([]*ast.Field, 0, len(serviceInfo.Methods))

	for _, method := range serviceInfo.Methods {
		endpointName := fmt.Sprintf("%s_%s", serviceInfo.Name, method.Name)
		if _, ok := ImplementedEndpoints[endpointName]; ok {
			methods = append(methods, mkServiceInterfaceMethod(method))
		}
	}

	// Create an interface declaration
	return &ast.GenDecl{
		Tok: token.TYPE, // Specifies a type declaration
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name: ast.NewIdent(serviceInfo.Name), // Interface name
				Type: &ast.InterfaceType{
					Methods: &ast.FieldList{
						List: methods,
					},
				},
			},
		},
	}
}

func saveASTToFile(fset *token.FileSet, file *ast.File, addComment bool, outputPath string) error {
	// Create or truncate the output file
	outputFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("could not create output file: %w", err)
	}
	defer outputFile.Close()

	// Use a bufio.Writer for buffered writing (optional)
	writer := bufio.NewWriter(outputFile)
	defer writer.Flush()

	if addComment {
		_, err := writer.WriteString("// Code generated by mlflow/go/tools/generate/main.go. DO NOT EDIT.\n\n")
		if err != nil {
			return fmt.Errorf("could not add comment to generated file: %w", err)
		}
	}

	// Write the generated code to the file
	err = format.Node(writer, fset, file)

	if err != nil {
		return fmt.Errorf("could not write generated AST to file: %w", err)
	}

	return nil
}

// fun(arg1, arg2, ...)
func mkCallExpr(fun ast.Expr, args ...ast.Expr) *ast.CallExpr {
	return &ast.CallExpr{
		Fun:  fun,
		Args: args,
	}
}

// Shorthand for creating &expr.
func mkAmpExpr(expr ast.Expr) *ast.UnaryExpr {
	return &ast.UnaryExpr{
		Op: token.AND,
		X:  expr,
	}
}

// err != nil.
var errNotEqualNil = &ast.BinaryExpr{
	X:  ast.NewIdent("err"),
	Op: token.NEQ,
	Y:  ast.NewIdent("nil"),
}

// return err.
var returnErr = &ast.ReturnStmt{
	Results: []ast.Expr{ast.NewIdent("err")},
}

func mkBlockStmt(stmts ...ast.Stmt) *ast.BlockStmt {
	return &ast.BlockStmt{
		List: stmts,
	}
}

func mkIfStmt(init ast.Stmt, cond ast.Expr, body *ast.BlockStmt) *ast.IfStmt {
	return &ast.IfStmt{
		Init: init,
		Cond: cond,
		Body: body,
	}
}

func mkAssignStmt(lhs, rhs []ast.Expr) *ast.AssignStmt {
	return &ast.AssignStmt{
		Lhs: lhs,
		Tok: token.DEFINE,
		Rhs: rhs,
	}
}

func mkReturnStmt(results ...ast.Expr) *ast.ReturnStmt {
	return &ast.ReturnStmt{
		Results: results,
	}
}

//nolint:funlen
func mkAppRoute(method discovery.MethodInfo, endpoint discovery.Endpoint) ast.Stmt {
	urlExpr := &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf(`"%s"`, endpoint.GetFiberPath())}

	// input := &protos.SearchExperiments
	inputExpr := mkAssignStmt(
		[]ast.Expr{ast.NewIdent("input")},
		[]ast.Expr{
			mkAmpExpr(&ast.CompositeLit{
				Type: mkSelectorExpr(method.PackageName, method.Input),
			}),
		})

	// if err := parser.ParseQuery(ctx, input); err != nil { return err }
	// if err := parser.ParseBody(ctx, input); err != nil { return err }
	var extractModel ast.Expr
	if endpoint.Method == http.MethodGet {
		extractModel = mkCallExpr(mkSelectorExpr("parser", "ParseQuery"), ast.NewIdent("ctx"), ast.NewIdent("input"))
	} else {
		extractModel = mkCallExpr(mkSelectorExpr("parser", "ParseBody"), ast.NewIdent("ctx"), ast.NewIdent("input"))
	}

	inputErrorCheck := mkIfStmt(
		mkAssignStmt([]ast.Expr{ast.NewIdent("err")}, []ast.Expr{extractModel}),
		errNotEqualNil,
		mkBlockStmt(returnErr),
	)

	// output, err := service.Method(input)
	outputExpr := mkAssignStmt([]ast.Expr{
		ast.NewIdent("output"),
		ast.NewIdent("err"),
	}, []ast.Expr{
		mkCallExpr(mkSelectorExpr("service", strcase.ToCamel(method.Name)), ast.NewIdent("input")),
	})

	// if err != nil {
	//     return err
	// }
	errorCheck := mkIfStmt(
		nil,
		errNotEqualNil,
		mkBlockStmt(
			mkReturnStmt(ast.NewIdent("err")),
		),
	)

	// return ctx.JSON(output)
	returnExpr := mkReturnStmt(mkCallExpr(mkSelectorExpr("ctx", "JSON"), ast.NewIdent("output")))

	// func(ctx *fiber.Ctx) error { .. }
	funcExpr := &ast.FuncLit{
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("ctx", mkStarExpr(mkSelectorExpr("fiber", "Ctx"))),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					mkField(ast.NewIdent("error")),
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				inputExpr,
				inputErrorCheck,
				outputExpr,
				errorCheck,
				returnExpr,
			},
		},
	}

	return &ast.ExprStmt{
		// app.Get("/mlflow/experiments/search", func(ctx *fiber.Ctx) error { .. })
		X: mkCallExpr(
			mkSelectorExpr("app", strcase.ToCamel(endpoint.Method)), urlExpr, funcExpr,
		),
	}
}

func mkRouteRegistrationFunction(serviceInfo discovery.ServiceInfo) *ast.FuncDecl {
	routes := make([]ast.Stmt, 0, len(serviceInfo.Methods))

	for _, method := range serviceInfo.Methods {
		for _, endpoint := range method.Endpoints {
			endpointName := fmt.Sprintf("%s_%s", serviceInfo.Name, method.Name)
			if _, ok := ImplementedEndpoints[endpointName]; ok {
				routes = append(routes, mkAppRoute(method, endpoint))
			}
		}
	}

	return &ast.FuncDecl{
		Name: ast.NewIdent(fmt.Sprintf("Register%sRoutes", serviceInfo.Name)),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("service", ast.NewIdent(serviceInfo.Name)),
					mkNamedField("parser", ast.NewIdent("HTTPRequestParser")),
					mkNamedField("app", mkStarExpr(ast.NewIdent("fiber.App"))),
				},
			},
		},
		Body: &ast.BlockStmt{
			List: routes,
		},
	}
}

// Generate the service interface and route registration functions.
func generateServices(pkgFolder string) error {
	decls := []ast.Decl{importStatements}

	services := discovery.GetServiceInfos()
	for _, serviceInfo := range services {
		decls = append(decls, mkServiceInterfaceNode(serviceInfo))
	}

	for _, serviceInfo := range services {
		decls = append(decls, mkRouteRegistrationFunction(serviceInfo))
	}

	// Set up the FileSet and the AST File
	fset := token.NewFileSet()

	pkg := "contract"

	file := &ast.File{
		Name:  ast.NewIdent(pkg),
		Decls: decls,
	}

	outputPath := filepath.Join(pkgFolder, pkg, "interface.g.go")

	return saveASTToFile(fset, file, true, outputPath)
}

var jsonFieldTagRegexp = regexp.MustCompile(`json:"([^"]+)"`)

// Inspect the AST of the incoming file and add a query annotation to the struct tags which have a json tag.
//
//nolint:funlen,cyclop
func addQueryAnnotation(generatedGoFile string) error {
	// Parse the file into an AST
	fset := token.NewFileSet()

	node, err := parser.ParseFile(fset, generatedGoFile, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	// Create an AST inspector to modify specific struct tags
	ast.Inspect(node, func(n ast.Node) bool {
		// Look for struct type declarations
		typeSpec, isTypeSpec := n.(*ast.TypeSpec)
		if !isTypeSpec {
			return true
		}

		structType, isStructType := typeSpec.Type.(*ast.StructType)

		if !isStructType {
			return true
		}

		// Iterate over fields in the struct
		for _, field := range structType.Fields.List {
			if field.Tag == nil {
				continue
			}

			tagValue := field.Tag.Value

			hasQuery := strings.Contains(tagValue, "query:")
			hasValidate := strings.Contains(tagValue, "validate:")
			validationKey := fmt.Sprintf("%s_%s", typeSpec.Name, field.Names[0])
			validationRule, needsValidation := validations[validationKey]

			if hasQuery && (!needsValidation || needsValidation && hasValidate) {
				continue
			}

			// With opening ` tick
			newTag := tagValue[0 : len(tagValue)-1]

			matches := jsonFieldTagRegexp.FindStringSubmatch(tagValue)
			if len(matches) > 0 && !hasQuery {
				// Modify the tag here
				// The json annotation could be something like `json:"key,omitempty"`
				// We only want the key part, the `omitempty` is not relevant for the query annotation
				key := matches[1]
				if strings.Contains(key, ",") {
					key = strings.Split(key, ",")[0]
				}
				// Add query annotation
				newTag += fmt.Sprintf(" query:\"%s\"", key)
			}

			if needsValidation {
				// Add validation annotation
				newTag += fmt.Sprintf(" validate:\"%s\"", validationRule)
			}

			// Closing ` tick
			newTag += "`"
			field.Tag.Value = newTag
		}

		return false
	})

	return saveASTToFile(fset, node, false, generatedGoFile)
}

func addQueryAnnotations(pkgFolder string) error {
	protoFolder := filepath.Join(pkgFolder, "protos")

	if _, pathError := os.Stat(protoFolder); os.IsNotExist(pathError) {
		//nolint:err113
		return fmt.Errorf("the %s folder does not exist. Are the Go protobuf files generated?", protoFolder)
	}

	err := filepath.WalkDir(protoFolder, func(path string, _ fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if filepath.Ext(path) == ".go" {
			err = addQueryAnnotation(path)
		}

		return err
	})

	if err != nil {
		return fmt.Errorf("could not add query annotation: %w", err)
	}

	return nil
}

const ExpectedNumberOfArguments = 2

//nolint:forbidigo
func main() {
	if len(os.Args) != ExpectedNumberOfArguments {
		fmt.Println("Usage: program <path to mlflow/go/pkg folder>")
		os.Exit(1)
	}

	pkgFolder := os.Args[1]
	if _, err := os.Stat(pkgFolder); os.IsNotExist(err) {
		fmt.Printf("The provided path does not exist: %s\n", pkgFolder)
		os.Exit(1)
	}

	if err := addQueryAnnotations(pkgFolder); err != nil {
		fmt.Printf("Error adding query annotations: %s\n", err)
		os.Exit(1)
	}

	if err := generateServices(pkgFolder); err != nil {
		fmt.Printf("Error generating services: %s\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully added query annotations and generated services!")
}
