FROM amd64/python:3.10

ARG DEPENDENCIES

# apt-get and system utilities
RUN apt-get update && apt-get install -y \
    curl apt-transport-https debconf-utils gpg \
    && rm -rf /var/lib/apt/lists/*

# adding custom MS repository
# https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver17&tabs=ubuntu2004#install-sql-server
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
RUN curl -fsSL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sed 's|deb |deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] |' > /etc/apt/sources.list.d/mssql-release.list

# install SQL Server drivers and tools
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

RUN pip install pyodbc pytest pytest-cov pytest-asyncio
RUN echo "${DEPENDENCIES}" > /tmp/requriements.txt && pip install -r /tmp/requriements.txt
RUN pip list
