version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s %(levelprefix)s %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: false
