"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ScalaPbOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACKAGE_NAME_FIELD_NUMBER: _builtins.int
    FLAT_PACKAGE_FIELD_NUMBER: _builtins.int
    IMPORT_FIELD_NUMBER: _builtins.int
    package_name: _builtins.str
    """If set then it overrides the java_package and package."""
    flat_package: _builtins.bool
    """If true, the compiler does not append the proto base file name
    into the generated package name. If false (the default), the
    generated scala package name is the package_name.basename where
    basename is the proto file name without the .proto extension.
    """
    def __init__(
        self,
        *,
        package_name: _builtins.str | None = ...,
        flat_package: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["flat_package", b"flat_package", "package_name", b"package_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flat_package", b"flat_package", "import", b"import", "package_name", b"package_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScalaPbOptions: _TypeAlias = ScalaPbOptions  # noqa: Y015

@_typing.final
class MessageOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXTENDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def extends(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """additional classes and traits to mix in to the case class."""

    def __init__(
        self,
        *,
        extends: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extends", b"extends"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MessageOptions: _TypeAlias = MessageOptions  # noqa: Y015

@_typing.final
class FieldOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    def __init__(
        self,
        *,
        type: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FieldOptions: _TypeAlias = FieldOptions  # noqa: Y015

OPTIONS_FIELD_NUMBER: _builtins.int
MESSAGE_FIELD_NUMBER: _builtins.int
FIELD_FIELD_NUMBER: _builtins.int
options: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, Global___ScalaPbOptions]
"""File-level optionals for ScalaPB.
Extension number officially assigned by protobuf-global-extension-registry@google.com
"""
message: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, Global___MessageOptions]
"""Message-level optionals for ScalaPB.
Extension number officially assigned by protobuf-global-extension-registry@google.com
"""
field: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, Global___FieldOptions]
"""File-level optionals for ScalaPB.
Extension number officially assigned by protobuf-global-extension-registry@google.com
"""
