FROM python:3.8

ARG MINIFORG_FILENAME=Miniforge3-Linux-x86_64.sh
ENV DEBIAN_FRONTEND=noninteractive \
    PATH=/opt/conda/bin:$PATH

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential openjdk-17-jre-headless \
    # cmake and protobuf-compiler required for onnx install
    cmake protobuf-compiler && \
    # Install miniforge
    wget -q https://github.com/conda-forge/miniforge/releases/latest/download/$MINIFORG_FILENAME && \
    bash $MINIFORG_FILENAME -b -p /opt/conda && \
    rm $MINIFORG_FILENAME

ADD ./requirements /app/requirements

ADD ./dev/clint /app/dev/clint

RUN \
    # install required python packages
    pip install -r requirements/test-requirements.txt --no-cache-dir \
        -r requirements/lint-requirements.txt

ADD . /app

RUN \
    # install mlflow in editable form
    pip install --no-cache-dir -e .

RUN \
    # clean cache
    apt-get autoremove -yqq --purge && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN \
    # adding an unprivileged user
    groupadd --gid 10001 mlflow && \
    useradd --uid 10001 --gid mlflow --shell /bin/bash --create-home mlflow

# the "mlflow" user created above, represented numerically for optimal compatibility with Kubernetes security policies
USER 10001

CMD ["bash"]
