FROM python:3.10-slim

WORKDIR /mlflow

RUN pip install protobuf packaging

# Copy only necessary files to compile protos
COPY mlflow/protos ./mlflow/protos/
COPY dev ./dev/
COPY tests/protos ./tests/protos/
