.git
mlruns
docs
apidocs
mlflow.Rcheck
outputs

dev
# required for Docker build
!requirements/test-requirements.txt
!requirements/lint-requirements.txt
!requirements/extra-ml-requirements.txt

*/node_modules
coverage
build
npm-debug.log*
yarn-debug.log*
yarn-error.log*
*/__pycache__
.*
~*
*.swp
*.pyc