name: "check-component-ids"
description: "Verify that all componentIds in the MLflow UI are registered in the componentId registry and vice versa."
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 20
    - run: node ${GITHUB_ACTION_PATH}/index.js
      shell: bash
