{{- if .Values.externalSecrets.enabled }}
{{- if not .Values.externalSecrets.data }}
{{- fail "externalSecrets.data is required (non-empty) when externalSecrets.enabled is true" }}
{{- end }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ printf "%s-externalsecret" (include "mlflow.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "mlflow.fullname" . }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName | default (include "mlflow.fullname" .) }}
    creationPolicy: Owner
    {{- with .Values.externalSecrets.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
