{{- if .Values.externalSecrets.enabled }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "mlflow.fullname" . }}-externalsecret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "mlflow.fullname" . }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName | default (include "mlflow.fullname" .) }}
    creationPolicy: Owner
    {{- with .Values.externalSecrets.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
