{{- if .Values.externalSecrets.enabled }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: SecretStore
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.externalSecrets.provider | nindent 4 }}
{{- end }}
