{{- if and .Values.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ if .Values.tls.enabled }}https{{ else }}http{{ end }}
      path: {{ .Values.metrics.path }}
      {{- if .Values.tls.enabled }}
      scheme: https
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
