version: "3"
services:
  storage:
    image: rustfs/rustfs:1.0.0-alpha.83
    expose:
      - "9000"
    ports:
      - "9000:9000"
      # RustFS Console is available at http://localhost:9001
      - "9001:9001"
    environment:
      RUSTFS_ADDRESS: :9000
      RUSTFS_SERVER_DOMAINS: storage:9000
      RUSTFS_REGION: us-east-1
      RUSTFS_ACCESS_KEY: "user"
      RUSTFS_SECRET_KEY: "password"
      RUSTFS_CONSOLE_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", 'curl -s http://127.0.0.1:9000/health | grep -q ''"status":"ok"''']
      interval: 1s
      timeout: 10s
      retries: 5
    # Note there is no bucket by default
    command: /data

  create-bucket:
    image: amazon/aws-cli:2.33.25
    depends_on:
      storage:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: "user"
      AWS_SECRET_ACCESS_KEY: "password"
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "
      set -e;
      if aws --endpoint-url=http://storage:9000 s3api head-bucket --bucket bucket 2>/dev/null; then
        echo 'bucket already exists'
      else
        aws --endpoint-url=http://storage:9000 s3api create-bucket --bucket bucket
      fi
      "

  artifacts-server:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    depends_on:
      create-bucket:
        condition: service_completed_successfully
    expose:
      - "5500"
    ports:
      - "5500:5500"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://storage:9000
      AWS_ACCESS_KEY_ID: "user"
      AWS_SECRET_ACCESS_KEY: "password"
      MLFLOW_SERVER_ENABLE_JOB_EXECUTION: "false"
      MLFLOW_SERVER_DISABLE_SECURITY_MIDDLEWARE: "true"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5500
      --artifacts-destination s3://bucket
      --gunicorn-opts "--log-level debug"
      --artifacts-only

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  tracking-server:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    depends_on:
      - postgres
      - artifacts-server
    expose:
      - "5000"
    ports:
      # MLflow UI is available at http://localhost:5000
      - "5000:5000"
    environment:
      MLFLOW_SERVER_ENABLE_JOB_EXECUTION: "false"
      MLFLOW_SERVER_DISABLE_SECURITY_MIDDLEWARE: "true"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://user:password@postgres:5432/db
      --default-artifact-root http://artifacts-server:5500/api/2.0/mlflow-artifacts/artifacts/experiments
      --gunicorn-opts "--log-level debug"

  client:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    depends_on:
      - tracking-server
    environment:
      MLFLOW_TRACKING_URI: http://tracking-server:5000
