FROM python:3.10-slim

WORKDIR /app

# Install packages required to interact with PostgreSQL and MinIO
RUN pip install --no-cache-dir psycopg2-binary boto3
# Install the dev version of mlflow via wheel
COPY dist ./dist
RUN pip install --no-cache-dir dist/mlflow-*.whl
