# Build an image that can serve mlflow models.
FROM ubuntu:24.04

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends wget curl nginx ca-certificates bzip2 build-essential cmake git-core

# Install Python (system default for Ubuntu 24.04 is 3.12)
RUN apt-get install -y --no-install-recommends python3 python3-venv python3-pip \
    && rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED \
    && ln -sf /usr/bin/python3 /usr/bin/python


# Setup Java
RUN apt-get install -y --no-install-recommends openjdk-11-jdk maven
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

WORKDIR /opt/mlflow

# Install MLflow from local source
COPY mlflow-project /opt/mlflow
RUN pip install /opt/mlflow

# Install minimal serving dependencies
RUN python -c "from mlflow.models.container import _install_pyfunc_deps;_install_pyfunc_deps(None, False)"

ENV MLFLOW_DISABLE_ENV_CREATION=False

# granting read/write access and conditional execution authority to all child directories
# and files to allow for deployment to AWS Sagemaker Serverless Endpoints
# (see https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html)
RUN chmod o+rwX /opt/mlflow/

# clean up apt cache to reduce image size
RUN rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python", "-c", "import sys; from mlflow.models import container as C; C._init(sys.argv[1], 'virtualenv')"]
