# Build an image that can serve mlflow models.
FROM ubuntu:24.04

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --no-install-recommends wget curl nginx ca-certificates bzip2 build-essential cmake git-core

# Install Python 3.11 from Ubuntu universe repository
RUN sed -i '/^Components:/s/$/ universe/' /etc/apt/sources.list.d/ubuntu.sources \
    && apt-get update \
    && apt-get install -y python3.11 python3.11-venv \
    && rm -f /usr/lib/python3.11/EXTERNALLY-MANAGED \
    && ln -sf /usr/bin/python3.11 /usr/bin/python \
    && python -m ensurepip --upgrade \
    && pip install --upgrade pip




WORKDIR /opt/mlflow

# Install MLflow from local source
COPY mlflow-project /opt/mlflow
RUN pip install /opt/mlflow

# Install minimal serving dependencies
RUN python -c "from mlflow.models.container import _install_pyfunc_deps;_install_pyfunc_deps(None, False)"

ENV MLFLOW_DISABLE_ENV_CREATION=False

# granting read/write access and conditional execution authority to all child directories
# and files to allow for deployment to AWS Sagemaker Serverless Endpoints
# (see https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html)
RUN chmod o+rwX /opt/mlflow/

# clean up apt cache to reduce image size
RUN rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python", "-c", "import sys; from mlflow.models import container as C; C._init(sys.argv[1], 'virtualenv')"]
