FROM python:3.10-slim-bullseye@sha256:f1fb49e4d5501ac93d0ca519fb7ee6250842245aba8612926a46a0832a1ed089

WORKDIR /app
ADD . /app

# Install MLflow from the current directory with extras
RUN pip install --no-cache-dir .[extras,azure,db,databricks,gateway,genai]
