# Build an image that can serve pyfunc model in SageMaker
# This is a dev version which installs local copy of mlflow rather than the one published at pip.
FROM ubuntu:16.04


RUN apt-get -y update && apt-get install -y --no-install-recommends \
         wget \
         curl \
         nginx \
         ca-certificates \
         bzip2 \
         build-essential \
         cmake \
         git-core \
    && rm -rf /var/lib/apt/lists/*

# Download and setup miniconda
RUN curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh >> miniconda.sh
RUN bash ./miniconda.sh -b -p /miniconda; rm ./miniconda.sh;
ENV PATH="/miniconda/bin:${PATH}"

# Set up the program in the image
COPY . /opt/mlflow
RUN rm -rf $(find /opt/mlflow/mlflow -name __pycache__)
RUN rm -rf $(find /opt/mlflow/mlflow -name *.pyc)


RUN conda install -c anaconda gunicorn;\
    conda install -c anaconda gevent;\
    pip install /opt/mlflow

# Set up the program in the image
WORKDIR /opt/mlflow

# start mlflow scoring
ENTRYPOINT ["python", "-c", "import sys; from mlflow.sagemaker import container; print(sys.argv); container._scoring_server_init(sys.argv[1])"]
