# Path to default location for backend when using local FileStore.
DEFAULT_LOCAL_FILE_AND_ARTIFACT_PATH = "./mlruns"

SEARCH_REGISTERED_MODEL_MAX_RESULTS_DEFAULT = 100
SEARCH_REGISTERED_MODEL_MAX_RESULTS_THRESHOLD = 1000
SEARCH_MODEL_VERSION_MAX_RESULTS_DEFAULT = 200_000
SEARCH_MODEL_VERSION_MAX_RESULTS_THRESHOLD = 200_000
