name: "validate-author"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const validateAuthor = require(
            `${process.env.GITHUB_WORKSPACE}/.github/actions/validate-author/index.js`
          );
          await validateAuthor({ context, github, core });
