export const LIST_SECRETS_QUERY_KEY = 'LIST_SECRETS';
export const LIST_BINDINGS_QUERY_KEY = 'LIST_BINDINGS';
export const LIST_ROUTES_QUERY_KEY = 'LIST_ROUTES';
export const LIST_ENDPOINTS_QUERY_KEY = 'LIST_ENDPOINTS';
