name: "setup-java"
description: "Set up Java"
inputs:
  java-version:
    description: "java-version"
    default: "17"
    required: false

  distribution:
    description: "distribution"
    default: temurin
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Set MLFLOW_DOCKER_OPENJDK_VERSION
      shell: bash
      env:
        JAVA_VERSION: ${{ inputs.java-version }}
      run: |
        echo "MLFLOW_DOCKER_OPENJDK_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
