"""Inspect AI scorer integration for MLflow.

This package exposes a lightweight MLflow scorer wrapper for Inspect AI.
It is the public entrypoint for users who want to call Inspect AI evaluation
metrics through MLflow's ``mlflow.genai.scorers`` third-party scorer API.

The implementation is intentionally minimal here so the package can expose a
stable public API while the underlying scoring and task-conversion details are
implemented in internal helper modules.
"""

from __future__ import annotations

import logging
from typing import Any

from pydantic import PrivateAttr

from mlflow.entities.assessment import Feedback
from mlflow.entities.assessment_source import AssessmentSource, AssessmentSourceType
from mlflow.entities.trace import Trace
from mlflow.exceptions import MlflowException
from mlflow.genai.judges.builtin import _MODEL_API_DOC
from mlflow.genai.judges.utils import get_default_model
from mlflow.genai.scorers import FRAMEWORK_METADATA_KEY
from mlflow.genai.scorers.base import Scorer, ScorerKind
from mlflow.utils.annotations import experimental
from mlflow.utils.docstring_utils import format_docstring

_logger = logging.getLogger(__name__)
_FRAMEWORK_NAME = "inspect_ai"


@experimental(version="3.12.0")
@format_docstring(_MODEL_API_DOC)
class InspectAIScorer(Scorer):
    """MLflow scorer wrapper for Inspect AI evaluation tasks.

    Args:
        metric_name: Name of the Inspect AI scorer or task to evaluate.
        model: Optional model URI to use when the Inspect AI scorer requires an LLM.
        model_kwargs: Optional keyword arguments for the underlying model.
        scorer_kwargs: Additional keyword arguments forwarded to the Inspect AI
            scorer/task implementation.
    """

    _metric_name: str = PrivateAttr(default="")
    _model: str | None = PrivateAttr(default=None)
    _metric_kwargs: dict[str, Any] = PrivateAttr(default_factory=dict)
    _model_kwargs: dict[str, Any] = PrivateAttr(default_factory=dict)
    _scorer_kwargs: dict[str, Any] = PrivateAttr(default_factory=dict)

    def __init__(
        self,
        metric_name: str | None = None,
        model: str | None = None,
        model_kwargs: dict[str, Any] | None = None,
        **scorer_kwargs: Any,
    ):
        if metric_name is None:
            raise MlflowException.invalid_parameter_value(
                "Inspect AI scorer requires a metric_name."
            )

        super().__init__(name=metric_name)
        self._metric_name = metric_name
        self._model = model or get_default_model()
        self._metric_kwargs = dict(model_kwargs or {})
        self._model_kwargs = dict(model_kwargs or {})
        self._scorer_kwargs = dict(scorer_kwargs)

    @property
    def kind(self) -> ScorerKind:
        """Return the scorer kind used by MLflow serialization."""
        return ScorerKind.THIRD_PARTY

    def model_dump(self, **kwargs: Any) -> dict[str, Any]:
        """Serialize the scorer, including Inspect AI-specific kwargs."""
        dump = super().model_dump(**kwargs)
        if self.kind == ScorerKind.THIRD_PARTY:
            data = dump.get("third_party_scorer_data", {})
            data["kwargs"] = {
                **data.get("kwargs", {}),
                **self._scorer_kwargs,
            }
            dump["third_party_scorer_data"] = data
        return dump

    def __call__(
        self,
        *,
        inputs: Any = None,
        outputs: Any = None,
        expectations: dict[str, Any] | None = None,
        trace: Trace | None = None,
        session: list[Trace] | None = None,
    ) -> Feedback:
        """Evaluate a single MLflow trace or session through Inspect AI.

        This method is synchronous to satisfy MLflow's ``Scorer`` interface,
        but it may call Inspect AI async internals lazily.

        Args:
            inputs: Input payload passed to the target model.
            outputs: Output generated by the target model.
            expectations: Ground-truth expectations or reference data.
            trace: Optional MLflow trace object for richer evaluation context.
            session: Optional list of MLflow traces for conversational scoring.

        Returns:
            Feedback object representing the Inspect AI score result.
        """
        assessment_source = AssessmentSource(
            source_type=AssessmentSourceType.LLM_JUDGE,
            source_id=self._model,
        )

        try:
            from mlflow.genai.scorers.inspect_ai.wrapper import score_with_inspect_ai

            feedback = score_with_inspect_ai(
                metric_name=self._metric_name,
                model=self._model,
                model_kwargs=self._model_kwargs,
                inputs=inputs,
                outputs=outputs,
                expectations=expectations,
                trace=trace,
                session=session,
                scorer_kwargs=self._scorer_kwargs,
            )

            feedback.source = assessment_source
            return feedback
        except Exception as exc:
            _logger.error("Inspect AI evaluation failed: %s", exc)
            return Feedback(
                name=self.name,
                error=exc,
                source=assessment_source,
                metadata={FRAMEWORK_METADATA_KEY: _FRAMEWORK_NAME},
            )


@experimental(version="3.12.0")
@format_docstring(_MODEL_API_DOC)
def get_scorer(
    metric_name: str,
    model: str | None = None,
    model_kwargs: dict[str, Any] | None = None,
    **scorer_kwargs: Any,
) -> InspectAIScorer:
    """Return an Inspect AI-backed MLflow scorer.

    Args:
        metric_name: Name of the Inspect AI scorer or task.
        model: Optional model URI for Inspect AI scoring.
        model_kwargs: Optional model keyword args for the underlying LLM.
        scorer_kwargs: Additional Inspect AI scoring options.

    Returns:
        InspectAIScorer instance that supports MLflow scorer evaluation.

    Example:
        >>> from mlflow.genai.scorers.inspect_ai import get_scorer
        >>> scorer = get_scorer("my_inspect_ai_scorer", model="openai:/gpt-4")
        >>> feedback = scorer(outputs="Answer", expectations={"label": "Yes"})
    """
    return InspectAIScorer(
        metric_name=metric_name,
        model=model,
        model_kwargs=model_kwargs,
        **scorer_kwargs,
    )


__all__ = ["InspectAIScorer", "get_scorer"]