"""Centralized error classification for MLflow exceptions.

Maps error codes to sqlstate codes and error classes for structured error
classification and observability. Client-side errors use the KAM0x/XXM0x
namespace, while server/CP errors use the KAMCx/XXMCx namespace.
"""

from enum import Enum


class SqlState(str, Enum):
    """SQLSTATE codes for MLflow error classification."""

    # Client user errors (KAM0x)
    CLIENT_INVALID_PARAMETER = "KAM00"
    CLIENT_SCHEMA_ENFORCEMENT_FAILED = "KAM01"
    CLIENT_PREDICTION_FUNCTION_FAILED = "KAM02"
    CLIENT_MODEL_SERIALIZATION_FAILED = "KAM03"
    CLIENT_ATTRIBUTE_NOT_FOUND = "KAM04"

    # Client system errors (XXM0x)
    CLIENT_INTERNAL_ERROR = "XXM00"

    # CP/server user errors (KAMCx)
    CP_PERMISSION_DENIED = "KAMC1"
    CP_RESOURCE_NOT_FOUND = "KAMC2"
    CP_REQUEST_RATE_LIMITED = "KAMC3"
    CP_INVALID_PARAMETER = "KAMC4"
    CP_RESOURCE_CONFLICT = "KAMC5"

    # CP/server system errors (XXMCx)
    CP_INTERNAL_ERROR = "XXMC0"
    CP_TEMPORARILY_UNAVAILABLE = "XXMC1"
    CP_INVALID_STATE = "XXMC2"


class ErrorClass(str, Enum):
    """Error class names for MLflow error classification."""

    # Client error classes
    INVALID_PARAMETER_VALUE = "INVALID_PARAMETER_VALUE"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    FEATURE_DISABLED = "FEATURE_DISABLED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    SCHEMA_ENFORCEMENT_FAILED = "SCHEMA_ENFORCEMENT_FAILED"
    PREDICTION_FUNCTION_FAILED = "PREDICTION_FUNCTION_FAILED"
    MODEL_SERIALIZATION_FAILED = "MODEL_SERIALIZATION_FAILED"
    ATTRIBUTE_NOT_FOUND = "ATTRIBUTE_NOT_FOUND"
    CLIENT_INTERNAL_ERROR = "CLIENT_INTERNAL_ERROR"

    # CP error classes
    CP_PERMISSION_DENIED = "CP_PERMISSION_DENIED"
    CP_RESOURCE_NOT_FOUND = "CP_RESOURCE_NOT_FOUND"
    CP_REQUEST_RATE_LIMITED = "CP_REQUEST_RATE_LIMITED"
    CP_INVALID_PARAMETER_VALUE = "CP_INVALID_PARAMETER_VALUE"
    CP_RESOURCE_CONFLICT = "CP_RESOURCE_CONFLICT"
    CP_INTERNAL_ERROR = "CP_INTERNAL_ERROR"
    CP_TEMPORARILY_UNAVAILABLE = "CP_TEMPORARILY_UNAVAILABLE"
    CP_INVALID_STATE = "CP_INVALID_STATE"


# Client-side mappings: error_code -> (sqlstate, error_class)
_CLIENT_ERROR_CODE_TO_SQLSTATE: dict[str, str] = {
    "INVALID_PARAMETER_VALUE": SqlState.CLIENT_INVALID_PARAMETER,
    "BAD_REQUEST": SqlState.CLIENT_INVALID_PARAMETER,
    "RESOURCE_DOES_NOT_EXIST": SqlState.CLIENT_INVALID_PARAMETER,
    "RESOURCE_ALREADY_EXISTS": SqlState.CLIENT_INVALID_PARAMETER,
    "NOT_FOUND": SqlState.CLIENT_INVALID_PARAMETER,
    "ENDPOINT_NOT_FOUND": SqlState.CLIENT_INVALID_PARAMETER,
    "FEATURE_DISABLED": SqlState.CLIENT_INVALID_PARAMETER,
    "PERMISSION_DENIED": SqlState.CLIENT_INVALID_PARAMETER,
    "CUSTOMER_UNAUTHORIZED": SqlState.CLIENT_INVALID_PARAMETER,
    "INTERNAL_ERROR": SqlState.CLIENT_INTERNAL_ERROR,
    "INVALID_STATE": SqlState.CLIENT_INTERNAL_ERROR,
    "TEMPORARILY_UNAVAILABLE": SqlState.CLIENT_INTERNAL_ERROR,
}

_CLIENT_ERROR_CODE_TO_ERROR_CLASS: dict[str, str] = {
    "INVALID_PARAMETER_VALUE": ErrorClass.INVALID_PARAMETER_VALUE,
    "BAD_REQUEST": ErrorClass.INVALID_PARAMETER_VALUE,
    "RESOURCE_DOES_NOT_EXIST": ErrorClass.RESOURCE_NOT_FOUND,
    "RESOURCE_ALREADY_EXISTS": ErrorClass.RESOURCE_ALREADY_EXISTS,
    "NOT_FOUND": ErrorClass.RESOURCE_NOT_FOUND,
    "ENDPOINT_NOT_FOUND": ErrorClass.RESOURCE_NOT_FOUND,
    "FEATURE_DISABLED": ErrorClass.FEATURE_DISABLED,
    "PERMISSION_DENIED": ErrorClass.PERMISSION_DENIED,
    "CUSTOMER_UNAUTHORIZED": ErrorClass.PERMISSION_DENIED,
    "INTERNAL_ERROR": ErrorClass.CLIENT_INTERNAL_ERROR,
    "INVALID_STATE": ErrorClass.CLIENT_INTERNAL_ERROR,
    "TEMPORARILY_UNAVAILABLE": ErrorClass.CLIENT_INTERNAL_ERROR,
}

# CP/server-side mappings: error_code -> (sqlstate, error_class)
_CP_ERROR_CODE_TO_SQLSTATE: dict[str, str] = {
    "PERMISSION_DENIED": SqlState.CP_PERMISSION_DENIED,
    "CUSTOMER_UNAUTHORIZED": SqlState.CP_PERMISSION_DENIED,
    "UNAUTHENTICATED": SqlState.CP_PERMISSION_DENIED,
    "RESOURCE_DOES_NOT_EXIST": SqlState.CP_RESOURCE_NOT_FOUND,
    "ENDPOINT_NOT_FOUND": SqlState.CP_RESOURCE_NOT_FOUND,
    "NOT_FOUND": SqlState.CP_RESOURCE_NOT_FOUND,
    "REQUEST_LIMIT_EXCEEDED": SqlState.CP_REQUEST_RATE_LIMITED,
    "RESOURCE_EXHAUSTED": SqlState.CP_REQUEST_RATE_LIMITED,
    "INVALID_PARAMETER_VALUE": SqlState.CP_INVALID_PARAMETER,
    "BAD_REQUEST": SqlState.CP_INVALID_PARAMETER,
    "RESOURCE_ALREADY_EXISTS": SqlState.CP_RESOURCE_CONFLICT,
    "RESOURCE_CONFLICT": SqlState.CP_RESOURCE_CONFLICT,
    "INTERNAL_ERROR": SqlState.CP_INTERNAL_ERROR,
    "TEMPORARILY_UNAVAILABLE": SqlState.CP_TEMPORARILY_UNAVAILABLE,
    "INVALID_STATE": SqlState.CP_INVALID_STATE,
}

_CP_ERROR_CODE_TO_ERROR_CLASS: dict[str, str] = {
    "PERMISSION_DENIED": ErrorClass.CP_PERMISSION_DENIED,
    "CUSTOMER_UNAUTHORIZED": ErrorClass.CP_PERMISSION_DENIED,
    "UNAUTHENTICATED": ErrorClass.CP_PERMISSION_DENIED,
    "RESOURCE_DOES_NOT_EXIST": ErrorClass.CP_RESOURCE_NOT_FOUND,
    "ENDPOINT_NOT_FOUND": ErrorClass.CP_RESOURCE_NOT_FOUND,
    "NOT_FOUND": ErrorClass.CP_RESOURCE_NOT_FOUND,
    "REQUEST_LIMIT_EXCEEDED": ErrorClass.CP_REQUEST_RATE_LIMITED,
    "RESOURCE_EXHAUSTED": ErrorClass.CP_REQUEST_RATE_LIMITED,
    "INVALID_PARAMETER_VALUE": ErrorClass.CP_INVALID_PARAMETER_VALUE,
    "BAD_REQUEST": ErrorClass.CP_INVALID_PARAMETER_VALUE,
    "RESOURCE_ALREADY_EXISTS": ErrorClass.CP_RESOURCE_CONFLICT,
    "RESOURCE_CONFLICT": ErrorClass.CP_RESOURCE_CONFLICT,
    "INTERNAL_ERROR": ErrorClass.CP_INTERNAL_ERROR,
    "TEMPORARILY_UNAVAILABLE": ErrorClass.CP_TEMPORARILY_UNAVAILABLE,
    "INVALID_STATE": ErrorClass.CP_INVALID_STATE,
}


def get_client_sqlstate(error_code: str) -> str | None:
    return _CLIENT_ERROR_CODE_TO_SQLSTATE.get(error_code)


def get_client_error_class(error_code: str) -> str | None:
    return _CLIENT_ERROR_CODE_TO_ERROR_CLASS.get(error_code)


def get_cp_sqlstate(error_code: str) -> str | None:
    return _CP_ERROR_CODE_TO_SQLSTATE.get(error_code)


def get_cp_error_class(error_code: str) -> str | None:
    return _CP_ERROR_CODE_TO_ERROR_CLASS.get(error_code)
