---
title: "mlflow Demo 2 - R"
output:
  html_document:
    df_print: paged
---

This notebook is an example of an R mlflow Run.  This Run is a continuation of the `mlflow_demo2` experiment

```{r}
library(mlflow)
library(glmnet)

set.seed(40)
```

Read the wine-quality csv file
 
```{r}
data <- read.csv("wine-quality.csv")
```

Split the data into training and test sets. (0.75, 0.25) split.

```{r}
sampled <- sample(1:nrow(data), 0.75 * nrow(data))
train <- data[sampled, ]
test <- data[-sampled, ]
```

The predicted column is "quality" which is a scalar from [3, 9]

```{r}
train_x <- as.matrix(train[, !(names(train) == "quality")])
test_x <- as.matrix(test[, !(names(train) == "quality")])
train_y <- train[, "quality"]
test_y <- test[, "quality"]
```

```{r}
alpha <- mlflow_param("alpha", 0.5, "numeric")
lambda <- mlflow_param("lambda", 0.5, "numeric")
```


```{r}


mlflow_set_tracking_uri("http://mlflow_tracker:5000")
mlflow_get_tracking_uri()


```
```{r}
experiment_id <- mlflow_set_experiment('mlflow_demo2')
experiment_id
```

```{r}
with(mlflow_start_run(experiment_id=experiment_id), {
    model <- glmnet(train_x, train_y, alpha = alpha, lambda = lambda, family = "gaussian")
    predictor <- crate(~ glmnet::predict.glmnet(model, as.matrix(.x)), model)
    predicted <- predictor(test_x)

    rmse <- sqrt(mean((predicted - test_y) ^ 2))
    mae <- mean(abs(predicted - test_y))
    r2 <- as.numeric(cor(predicted, test_y) ^ 2)

    message("Elasticnet model (alpha=", alpha, ", lambda=", lambda, "):")
    message("  RMSE: ", rmse)
    message("  MAE: ", mae)
    message("  R2: ", r2)

    mlflow_log_param("alpha", alpha)
    mlflow_log_param("lambda", lambda)
    mlflow_log_param('algorithm','r-glmnet')
    mlflow_log_param('data_set_type','r_raw_data_set')
    
    mlflow_log_metric("r2", r2)
    
    mlflow_set_tag('estimator','glmnet')
    mlflow_set_tag('data_set_type','r_raw_data_set')

    mlflow_log_model(predictor, "model")
})
```

