// Code generated by mlflow/go/tools/generate/main.go. DO NOT EDIT.

package contract

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mlflow/mlflow/mlflow/go/pkg/protos"
)

type MlflowService interface {
	CreateExperiment(input *protos.CreateExperiment) (*protos.CreateExperiment_Response, *Error)
	GetExperiment(input *protos.GetExperiment) (*protos.GetExperiment_Response, *Error)
}
type ModelRegistryService interface {
}
type MlflowArtifactsService interface {
}

func RegisterMlflowServiceRoutes(service MlflowService, parser HttpRequestParser, app *fiber.App) {
	app.Post("/mlflow/experiments/create", func(ctx *fiber.Ctx) error {
		input := &protos.CreateExperiment{}
		if err := parser.ParseBody(ctx, input); err != nil {
			return err
		}
		output, err := service.CreateExperiment(input)
		if err != nil {
			return err
		}
		return ctx.JSON(output)
	})
	app.Get("/mlflow/experiments/get", func(ctx *fiber.Ctx) error {
		input := &protos.GetExperiment{}
		if err := parser.ParseQuery(ctx, input); err != nil {
			return err
		}
		output, err := service.GetExperiment(input)
		if err != nil {
			return err
		}
		return ctx.JSON(output)
	})
}
func RegisterModelRegistryServiceRoutes(service ModelRegistryService, parser HttpRequestParser, app *fiber.App) {
}
func RegisterMlflowArtifactsServiceRoutes(service MlflowArtifactsService, parser HttpRequestParser, app *fiber.App) {
}
