import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: 'doc',
      id: 'overview',
      className: 'sidebar-top-level-category',
    },
    {
      type: 'doc',
      id: 'getting-started/index',
      label: 'Getting Started',
      className: 'sidebar-top-level-category',
    },
    {
      type: 'category',
      label: 'Machine Learning 🧠',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'llms/index',
          label: 'LLM / GenAI',
        },
        {
          type: 'doc',
          id: 'deep-learning/index',
        },
        {
          type: 'doc',
          id: 'traditional-ml/index',
        },
      ],
    },
    {
      type: 'category',
      label: 'Build 🔨 ',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'MLflow Tracking',
          items: [
            {
              type: 'doc',
              id: 'tracking/index',
            },
            {
              type: 'doc',
              id: 'getting-started/intro-quickstart/index',
              label: 'Quickstart',
            },
            {
              type: 'doc',
              id: 'tracking/autolog/index',
            },
            {
              type: 'category',
              label: 'Tracking Server',
              items: [
                {
                  type: 'doc',
                  id: 'tracking/artifacts-stores/index',
                },
                {
                  type: 'doc',
                  id: 'tracking/backend-stores/index',
                },
                {
                  type: 'category',
                  label: 'Tutorials',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tracking/tutorials',
                    }
                  ],
                }
              ],
              link: {
                type: 'doc',
                id: 'tracking/server/index',
              }
            },
            {
              type: 'category',
              label: 'Searching Runs & Experiments',
              items: [
                {
                  type: 'doc',
                  id: 'tracking/search-runs/index',
                },
                {
                  type: 'doc',
                  id: 'tracking/search-experiments/index',
                }
              ]
            }
          ],
          link: {
            type: 'doc',
            id: 'tracking/index',
          },
        },
        {
          type: 'category',
          label: 'MLflow Model',
          items: [
            {
              type: 'autogenerated',
              dirName: 'model',
            },
          ],
        },
        {
          type: 'doc',
          id: 'recipes/index'
        }
      ]
    },
    {
      type: 'category',
      label: 'Evaluate & Monitor 📊',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'model-evaluation/index',
          label: 'MLflow Evaluation',
        },
        {
          type: 'category',
          label: 'MLflow Tracing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'tracing',
            },
          ],
          link: {
            type: 'doc',
            id: 'tracing/index',
          }
        },
        {
          type: 'doc',
          id: 'dataset/index',
          label: 'MLflow Dataset',
        },
      ]
    },
    {
      type: 'category',
      label: 'Deploy 🚀',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'model-registry/index',
        },
        {
          type: 'doc',
          id: 'deployment/index',
          label: 'MLflow Deployment',
        },
        {
          type: 'doc',
          id: 'llms/deployments/index',
          label: 'MLflow AI Gateway',
        },
      ]
    },
    {
      type: 'category',
      label: 'Team Collaboration 👥',
      className: 'sidebar-top-level-category',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'tracking/index',  // replace with platform page once added
          label: 'Self-Hosting'
        },
        {
          type: 'doc',
          id: 'tracking/index',  // replace with platform page once added
          label: 'Managed Services'
        },
        {
          type: 'doc',
          id: 'auth/index',
          label: 'Access Control',
        },
        {
          type: 'doc',
          id: 'projects/index',
          label: 'MLflow Projects',
        },
      ]
    },
    {
      type: 'category',
      label: 'API References',
      className: 'sidebar-top-level-category',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Python API',
          href: 'https://mlflow.org/docs/latest/python_api/index.html',
        },
        {
          type: 'link',
          label: 'Java API',
          href: 'https://mlflow.org/docs/latest/java_api/index.html',
        },
        {
          type: 'link',
          label: 'R API',
          href: 'https://mlflow.org/docs/latest/R-api/index.html',
        },
        {
          type: 'link',
          label: 'REST API',
          href: 'https://mlflow.org/docs/latest/rest-api/index.html',
        },
        {
          type: 'link',
          label: 'CLI',
          href: 'https://mlflow.org/docs/latest/cli.html',
        }
      ]
    },
    {
      type: 'category',
      label: 'More',
      collapsed: true,
      className:'sidebar-top-level-category',
      items: [
        {
          type: 'link',
          label: 'Contributing',
          href: 'https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.md',
        },
        {
          type: 'doc',
          id: 'plugins/index',
        },
        {
          type: 'link',
          label: 'MLflow Blogs',
          href: 'https://mlflow.org/blog/index.html',
        },
      ]
    },
  ]
};

export default sidebars;
