import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsGenAI: SidebarsConfig = {
  genAISidebar: [
    {
      type: 'doc',
      id: 'index',
      className: 'sidebar-top-level-category'
    },
    {
      type: 'category',
      label: 'Overview 🌟',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'overview/key-challenges',
          label: 'Key Challenges',
        },
        {
          type: 'doc',
          id: 'overview/why-mlflow',
          label: 'Why use MLflow',
        },
      ],
      link: {
        type: 'doc',
        id: 'overview/index',
      }
    },
    {
      type: 'category',
      label: 'Developer Workflow 👉',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'doc',
          id: 'developer-workflow/phase1-build-improve',
          label: 'Building & Iterating',
        },
        {
          type: 'doc',
          id: 'developer-workflow/phase2-systematically-test',
          label: 'Evaluate & Test',
        },
        {
          type: 'doc',
          id: 'developer-workflow/phase3-monitor',
          label: 'Monitor in Production',
        },
      ],
      link: {
        type: 'doc',
        id: 'developer-workflow/index',
      }
    },
    {
      type: 'category',
      label: 'Getting Started 🚀',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'doc',
          id: 'getting-started/connect-environment',
          label: 'Connect to MLflow',
        },
        {
          type: 'link',
          href: 'https://docs.databricks.com/aws/en/mlflow3/genai/getting-started/eval.html',
          label: 'Evaluate your GenAI App',
        },
        {
          type: 'category',
          label: 'Tracing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/tracing',
            }
          ],
          link: {
            type: 'doc',
            id: 'getting-started/tracing/index',
          }
        }
      ],
      link: {
        type: 'doc',
        id: 'getting-started/index'
      }
    },
    {
      type: 'category',
      label: 'Tutorials 🎓',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'doc',
          id: 'tutorials/debug-tracing',
          label: 'App Debugging with Tracing',
        },
        {
          type: 'doc',
          id: 'tutorials/dev-quality-iteration',
          label: 'Iterate on Quality during Development',
        },
        {
          type: 'doc',
          id: 'tutorials/enhance-quality',
          label: 'Using Traces for Quality Enhancement',
        },
        {
          type: 'doc',
          id: 'tutorials/jupyter-trace-demo-ipynb',
          label: 'Using Tracing in Jupyter Notebooks',
        }
      ],
      link: {
        type: 'doc',
        id: 'tutorials/index'
      }
    },
    {
      type: 'category',
      label: 'Tracing (Observability) 🔎',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'doc',
          id: 'tracing/quickstart',
          label: 'Quickstart',
        },
        {
          type: 'category',
          label: 'Instrumenting GenAI Apps',
          items: [
            {
              type: 'doc',
              id: 'tracing/app-instrumentation/automatic'
            },
            {
              type: 'category',
              label: 'Manual Tracing',
              items: [
                {
                  type: 'doc',
                  id: 'tracing/app-instrumentation/manual-tracing/fluent-apis',
                },
                {
                  type: 'doc',
                  id: 'tracing/app-instrumentation/manual-tracing/low-level-api'
                }
              ],
              link: {
                type: 'doc',
                id: 'tracing/app-instrumentation/manual-tracing/index'
              },
            },
          ],
          link: {
            type: 'doc',
            id: 'tracing/app-instrumentation/index'
          },
        },
        {
          type: 'category',
          label: 'Tracing Integrations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'tracing/integrations/listing'
            },
            {
              type: 'doc',
              id: 'tracing/integrations/contribute',
            },
          ],
          link: {
            type: 'doc',
            id: 'tracing/integrations/index',
          },
        },
        {
          type: 'category',
          label: 'Concepts',
          items: [
            {
              type: 'doc',
              id: 'tracing/concepts/trace-instrumentation'
            },
            {
              type: 'doc',
              id: 'tracing/data-model',
              label: 'Tracing Data Model',
            },
            {
              type: 'doc',
              id: 'tracing/concepts/trace/feedback',
            },
          ],
          link: {
            type: 'doc',
            id: 'tracing/concepts/trace-instrumentation'
          }
        },
        {
          type: 'category',
          label: 'Guides',
          items: [
            {
              type: 'doc',
              id: 'tracing/track-users-sessions/index',
              label: 'Track Users and Sessions',
            },
            {
              type: 'doc',
              id: 'tracing/track-environments-context/index',
              label: 'Track App Versions and Environments',
            },
            {
              type: 'doc',
              id: 'tracing/collect-user-feedback/index',
              label: 'User Feedback Collection',
            },
            {
              type: 'doc',
              id: 'tracing/attach-tags/index',
              label: 'Trace Tagging',
            },
            {
              type: 'doc',
              id: 'tracing/quality-with-traces',
              label: 'Using Traces for Quality Improvement',
            },
            {
              type: 'doc',
              id: 'tracing/observe-with-traces/delete-traces',
            },
            {
              type: 'doc',
              id: 'tracing/search-traces',
              label: 'Searching for Traces',
            },
          ],
        },

        {
          type: 'category',
          label: 'Observe & Analyze Traces',
          items: [
            {
              type: 'doc',
              id: 'tracing/observe-with-traces/ui',
            },
            {
              type: 'doc',
              id: 'tracing/observe-with-traces/query-via-sdk',
            },
          ],
          link: {
            type: 'doc',
            id: 'tracing/observe-with-traces/index'
          },
        },
        {
          type: 'doc',
          id: 'tracing/lightweight-sdk',
          label: 'Lightweight Tracing SDK',
        },
        {
          type: 'doc',
          id: 'tracing/prod-tracing',
          label: 'Production Tracing',
        },
        {
          type: 'doc',
          id: 'tracing/faq',
          label: 'Tracing FAQ'
        },
      ],
      link: {
        type: 'doc',
        id: 'tracing/index'
      }
    },
    {
      type: 'category',
      label: 'Evaluation 📊',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'category',
          label: 'Concepts & Reference',
          items: [
            {
              type: 'doc',
              id: 'eval-monitor/concepts/built-in-scorers',
              label: 'Built-in Scorers',
            },
            {
              type: 'doc',
              id: 'eval-monitor/concepts/eval-datasets',
              label: 'Evaluation Datasets',
            },
            {
              type: 'doc',
              id: 'eval-monitor/concepts/eval-harness',
              label: 'Evaluation Harness',
            },
            {
              type: 'doc',
              id: 'eval-monitor/concepts/evaluation-runs',
              label: 'Evaluation Runs',
            },
            {
              type: 'doc',
              id: 'eval-monitor/concepts/production-monitoring',
              label: 'Production Monitoring',
            },
            {
              type: 'doc',
              id: 'eval-monitor/concepts/scorers',
              label: 'Scorers',
            },
            {
              type: 'doc',
              id: 'eval-monitor/concepts/scorer-judge',
              label: 'Scorers, Feedback and Judges',
            },
            {

            },
            {
              type: 'category',
              label: 'Judges',
              items: [
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/guidelines',
                  label: 'Guidelines Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/is-context-relevant',
                  label: 'Relevancy Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/is-context-sufficient',
                  label: 'Sufficient Context Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/is-correct',
                  label: 'Correctness Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/is-grounded',
                  label: 'Grounded Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/is-safe',
                  label: 'Safety Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/pre-built-judges-scorers',
                  label: 'Pre-built Judges',
                },
                {
                  type: 'doc',
                  id: 'eval-monitor/concepts/judges/prompt-based-judge',
                  label: 'Prompt-based Judges',
                },
              ],
              link: {
                type: 'doc',
                id: 'eval-monitor/concepts/judges/index'
              }
            },
          ],
          link: {
            type: 'doc',
            id: 'eval-monitor/concepts/index'
          },
        },
        {
          type: 'doc',
          id: 'eval-monitor/quickstart',
          label: "Quickstart"
        },
        {
          type: 'category',
          label: 'Custom Judges',
          items: [
            {
              type: 'doc',
              id: 'eval-monitor/custom-judge/create-prompt-judge',
              label: 'Prompt Judges'
            },
            {
              type: 'doc',
              id: 'eval-monitor/custom-judge/meets-guidelines',
              label: 'Guidelines Judges'
            },
            {
              type: 'doc',
              id: 'eval-monitor/custom-judge/tune-judge',
              label: 'Tuning Custom Judges',
            }
          ],
          link: {
            type: 'doc',
            id: 'eval-monitor/custom-judge/index'
          }
        },
        {
          type: 'category',
          label: 'Guides',
          items: [
            {
              type: 'doc',
              id: 'eval-monitor/build-eval-dataset',
              label: 'Build an Evaluation Dataset',
            },
            {
              type: 'doc',
              id: 'eval-monitor/predefined-judge-scorers',
              label: 'Pre-Defined Scorers',
            },
            {
              type: 'doc',
              id: 'eval-monitor/custom-scorers',
              label: 'Custom Scorers',
            },
            {
              type: 'doc',
              id: 'eval-monitor/evaluate-app',
              label: 'Evaluate App Versions',
            },
            {
              type: 'doc',
              id: 'eval-monitor/version-comparison',
              label: 'Compare App Versions',
            },
            {
              type: 'doc',
              id: 'eval-monitor/ci-cd-testing',
              label: 'Evaluate within a CI/CD pipeline',
            },
            {
              type: 'doc',
              id: 'eval-monitor/continuous-improvement-with-production-data',
              label: 'Evaluate with Production Data',
            },
            {
              type: 'doc',
              id: 'eval-monitor/run-scorer-in-prod',
              label: 'Production Monitoring'
            },
          ]
        },
      ],
      link: {
        type: 'doc',
        id: 'eval-monitor/index'
      }
    },
    {
      type: 'category',
      label: 'Prompt and Version Management 🔨',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Version Tracking',
          items: [
            {
              type: 'doc',
              id: 'prompt-version-mgmt/version-tracking/quickstart',
              label: 'Quickstart',
            },
            {
              type: 'category',
              label: 'Guides',
              items: [
                {
                  type: 'doc',
                  id: 'prompt-version-mgmt/version-tracking/track-application-versions-with-mlflow',
                },
                {
                  type: 'doc',
                  id: 'prompt-version-mgmt/version-tracking/link-evaluation-results-and-traces-to-app-versions',
                },
                {
                  type: 'doc',
                  id: 'prompt-version-mgmt/version-tracking/compare-app-versions',
                },
                {
                  type: 'doc',
                  id: 'prompt-version-mgmt/version-tracking/optionally-package-app-code-and-files-for-databricks-model-serving',
                },
                {
                  type: 'doc',
                  id: 'prompt-version-mgmt/version-tracking/link-production-traces-to-app-versions'
                },
              ]
            }
          ],
          link: {
            type: 'doc',
            id: 'prompt-version-mgmt/version-tracking/index'
          }
        },
        {
          type: 'category',
          label: 'Prompt Registry',
          items: [
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/create-and-edit-prompts',
            },
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/evaluate-prompts',
            },
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/manage-prompt-lifecycles-with-aliases',
            },
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/optimize-prompts',
            },
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/use-prompts-in-apps',
            },
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/log-with-model',
            },
            {
              type: 'doc',
              id: 'prompt-version-mgmt/prompt-registry/use-prompts-in-deployed-apps',
            },
          ],
          link: {
            type: 'doc',
            id: 'prompt-version-mgmt/prompt-registry/index'
          }
        },
        {
          type: 'doc',
          id: 'prompt-version-mgmt/prompt-engineering/index',
          label: 'Prompt Engineering UI',
        }
      ]
    },
    {
      type: 'category',
      label: 'Integrations 🤖',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'category',
          label: 'OpenAI',
          items: [
            {
              type: 'doc',
              id: 'flavors/openai/guide/index',
              label: 'Guide'
            },
            {
              type: 'doc',
              id: 'flavors/openai/autologging/index',
              label: "Autologging Support",
            },
            {
              type: 'category',
              label: 'Tutorials',
              items: [
                {
                  type: 'doc',
                  id: 'flavors/openai/notebooks/openai-quickstart-ipynb',
                  label: 'OpenAI Quickstart'
                },
                {
                  type: 'doc',
                  id: 'flavors/openai/notebooks/openai-chat-completions-ipynb',
                  label: 'Chat Completions with OpenAI'
                },
                {
                  type: 'doc',
                  id: 'flavors/openai/notebooks/openai-code-helper-ipynb',
                  label: 'Building a Code Assistant with OpenAI & MLflow'
                },
                {
                  type: 'doc',
                  id: 'flavors/openai/notebooks/openai-embeddings-generation-ipynb',
                  label: 'Embeddings Support with OpenAI in MLflow'
                },
              ],
              link: {
                type: 'doc',
                id: 'flavors/openai/notebooks/index'
              }
            }
          ],
          link: {
            type: 'doc',
            id: 'flavors/openai/index'
          }
        },
        {
          type: 'category',
          label: 'DSPy',
          items: [
            {
              type: 'doc',
              id: 'flavors/dspy/notebooks/dspy_quickstart-ipynb',
              label: 'DSPy Quickstart',
            },
            {
              type: 'doc',
              id: 'flavors/dspy/optimizer',
              label: 'Using DSPy Optimizers',
            },
          ],
          link: {
            type: 'doc',
            id: 'flavors/dspy/index'
          }
        },
        {
          type: 'category',
          label: 'LangChain',
          items: [
            {
              type: 'doc',
              id: 'flavors/langchain/guide/index',
              label: 'Guide to using LangChain with MLflow'
            },
            {
              type: 'doc',
              id: 'flavors/langchain/notebooks/langchain-quickstart-ipynb',
              label: 'LangChain Quickstart',
            },
            {
              type: 'doc',
              id: 'flavors/langchain/notebooks/langchain-retriever-ipynb',
              label: 'Retrievers with LangChain',
            }
          ],
          link: {
            type: 'doc',
            id: 'flavors/langchain/index'
          }
        },
        {
          type: 'category',
          label: 'LlamaIndex',
          items: [
            {
              type: 'doc',
              id: 'flavors/llama-index/notebooks/llama_index_quickstart-ipynb',
              label: 'LlamaIndex Quickstart',
            },
            {
              type: 'doc',
              id: 'flavors/llama-index/notebooks/llama_index_workflow_tutorial-ipynb',
              label: 'Agents with LlamaIndex',
            }
          ],
          link: {
            type: 'doc',
            id: 'flavors/llama-index/index'
          }
        },
        {
          type: 'category',
          label: 'Custom Applications',
          items: [
            {
              type: 'doc',
              id: 'flavors/custom-pyfunc-for-llms/notebooks/custom-pyfunc-advanced-llm-ipynb',
              label: 'Custom App Development Guide',
            },
            {
              type: 'doc',
              id: 'flavors/chat-model-intro/index',
              label: 'Intro to ChatModel',
            },
            {
              type: 'category',
              label: 'Building with ChatModel',
              items: [
                {
                  type: 'doc',
                  id: 'flavors/chat-model-guide/chat-model-tool-calling-ipynb',
                  label: "ChatModel Tool Calling Example",
                }
              ],
              link: {
                type: 'doc',
                id: 'flavors/chat-model-guide/index',
              }
            },
            {
              type: 'doc',
              id: 'flavors/responses-agent-intro',
              label: 'Building with ResponsesAgent',
            },
          ],
          link: {
            type: 'doc',
            id: 'flavors/custom-pyfunc-for-llms/index'
          }
        },
      ],
      link: {
        type: 'doc',
        id: 'flavors/index',
      }
    },
    {
      type: 'category',
      label: 'Application Serving ⛵',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'doc',
          id: 'serving/responses-agent',
          label: 'Responses Agent',
        },
        {
          type: 'doc',
          id: 'serving/custom-apps',
          label: 'Custom Apps'
        },
        {
          type: 'doc',
          id: 'serving/endpoint-creation',
          label: 'Creating an Endpoint'
        }
      ],
      link: {
        type: 'doc',
        id: 'serving/index'
      }
    },
    {
      type: 'category',
      label: 'Governance 🛡️',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'category',
          label: 'AI Gateway',
          items: [
            {
              type: 'doc',
              id: 'governance/ai-gateway/guides/index',
              label: 'Getting Started with AI Gateway',
            },
            {
              type: 'doc',
              id: 'governance/ai-gateway/guides/step1-create-deployments/index',
              label: 'Setup the AI Gateway',
            },
            {
              type: 'doc',
              id: 'governance/ai-gateway/guides/step2-query-deployments/index',
              label: 'Use the AI Gateway',
            },
          ],
          link: {
            type: 'doc',
            id: 'governance/ai-gateway/index',
          },
        },
        {
          type: 'doc',
          id: 'governance/unity-catalog',
          label: 'Unity Catalog'
        }
      ],
      link: {
        type: 'doc',
        id: 'governance/ai-gateway/index'
      }
    },
    {
      type: 'category',
      label: 'Data Model 🧩',
      className: 'sidebar-top-level-category',
      items: [
        {
          type: 'doc',
          id: 'data-model/experiments',
          label: 'Experiments',
        },
        {
          type: 'doc',
          id: 'data-model/logged-model',
          label: 'Logged Model',
        },
        {
          type: 'doc',
          id: 'data-model/runs',
          label: 'Runs',
        },
        {
          type: 'doc',
          id: 'data-model/traces',
          label: 'Traces',
        },
        {
          type: 'doc',
          id: 'data-model/prompts',
          label: 'Prompts',
        },
        {
          type: 'doc',
          id: 'data-model/app-versions',
          label: 'Version Tracking',
        },
        {
          type: 'doc',
          id: 'data-model/model-registry',
          label: 'Model Registry',
        },
      ],
      link: {
        type: 'doc',
        id: 'data-model/index'
      }
    }
  ],
};

export default sidebarsGenAI;