import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsClassicML: SidebarsConfig = {
  classicMLSidebar: [
    {
      type: 'doc',
      id: 'index',
      className: 'sidebar-top-level-category'
    },
    {
      type: 'category',
      label: 'Build 🔨 ',
      className: 'sidebar-top-level-category',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'MLflow Tracking 📈',
          items: [
            {
              type: 'link',
              href: '/getting-started/intro-quickstart/',
              label: 'Quickstart ⚡',
            },
            {
              type: 'doc',
              id: 'tracking/autolog/index',
              label: 'Auto Logging 🤖',
            },
            {
              type: 'category',
              label: 'Tracking Server 🖥️',
              items: [
                {
                  type: 'doc',
                  id: 'tracking/artifacts-stores/index',
                },
                {
                  type: 'doc',
                  id: 'tracking/backend-stores/index',
                },
                {
                  type: 'category',
                  label: 'Tutorials',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'tracking/tutorials',
                    }
                  ],
                }
              ],
              link: {
                type: 'doc',
                id: 'tracking/server/index',
              }
            },
            {
              type: 'category',
              label: 'Search 🔍',
              items: [
                {
                  type: 'doc',
                  id: 'search-runs/index',
                },
                {
                  type: 'doc',
                  id: 'search-experiments/index',
                }
              ]
            },
            {
              type: 'doc',
              id: 'system-metrics/index',
            }
          ],
          link: {
            type: 'doc',
            id: 'tracking/index',
          },
        },
        {
          type: 'category',
          label: 'MLflow Model 🧠',
          items: [
            {
              type: 'autogenerated',
              dirName: 'model',
            },
          ],
        },
      ]
    },

    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: ['installation', 'quickstart'],
    // },
    // {
    //   type: 'category',
    //   label: 'Core Features',
    //   items: ['tracking', 'projects', 'model', 'model-registry'],
    // },
    // Add other categories and items as needed
  ],
};

export default sidebarsClassicML;