name: Auto Close PR

on:
  pull_request_target:
    types:
      - opened
      - reopened

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  auto-close-pr:
    if: >-
      !contains(fromJson('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association)
      && github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          retries: 3
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/.github/workflows/auto-close-pr.js`
            );
            await script.main({ context, github });
