on:
  push:
    branches:
      - feature/infra

    paths-ignore:
      - "**/README.md"
      - "terraform/**"
      - "terragrunt/**"

name: Uploading Image to dev

jobs:
  upload_to_ecr:
    name: Deploy to dev
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update host value in keycloak_auth.ini
        run: |
          NEW_HOST="https://identity.dev.nuoclient.nuodata.io/"
          CONFIG_FILE="/home/runner/work/nuodata-mlflow/nuodata-mlflow/mlflow/server/keycloak_auth/keycloak_auth.ini"
          sed -i "s|^host = .*|host = ${NEW_HOST}|" $CONFIG_FILE
          cat $CONFIG_FILE
      
      - name: Update Keycloak URL and Client ID in keycloak-config.ts
        run: |
          KEYCLOAK_URL="https://identity.dev.nuoclient.nuodata.io/"
          CLIENT_ID="nuodata-website"
          CONFIG_FILE="/home/runner/work/nuodata-mlflow/nuodata-mlflow/mlflow/server/js/src/keycloak-config.ts"
          sed -i "s|url: '.*'|url: '${KEYCLOAK_URL}'|" $CONFIG_FILE
          sed -i "s|clientId: '.*'|clientId: '${CLIENT_ID}'|" $CONFIG_FILE
          cat $CONFIG_FILE
      
      - name: Update .env File
        run: |
          CONFIG_FILE="/home/runner/work/nuodata-mlflow/nuodata-mlflow/mlflow/server/js/.env"
          PROD_REACT_APP_WEB_BASE_URL="https://aiml.dev.nuoclient.nuodata.io/"
          sed -i "s|REACT_APP_WEB_BASE_URL=.*|REACT_APP_WEB_BASE_URL=${PROD_REACT_APP_WEB_BASE_URL}|" $CONFIG_FILE
          cat $CONFIG_FILE

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACC_ID_DEV}}:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nuodata-dev-mlflow-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ssm put-parameter --name nuodata-dev-mlflow-img-ver --value $IMAGE_TAG --type String --overwrite
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f nuodata/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
