name: Dependabot Auto Merge

on:
  pull_request_target:
    types: [opened]
    paths:
      - .github/workflows/*.yml
      - .github/actions/*/action.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

permissions: {}
cache-mode: none

jobs:
  enable-auto-merge:
    if: >-
      github.repository == 'mlflow/mlflow'
      && github.event.pull_request.user.login == 'dependabot[bot]'
      && !github.event.pull_request.draft
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
          || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: mlflow
          repositories: mlflow
          permission-contents: write
          permission-pull-requests: write
      - name: Enable auto-merge
        if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
          || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: gh pr merge "$PR_URL" --auto --squash --match-head-commit "$HEAD_SHA"
