module.exports = async ({ github, context }) => {
  const { owner, repo } = context.repo;
  const pr = context.payload.pull_request.number;
  const sha = context.payload.pull_request.head.sha;
  const token = process.env.GITHUB_TOKEN;

  const GENERATED = [
    /^mlflow\/protos\/.*\.pyi$/,
    /_pb2(_grpc)?\.py$/,
    /^uv\.lock$/,
    /package-lock\.json$/,
    /yarn\.lock$/,
    /^docs\/api_reference\/source\/rest-api\.rst$/,
  ];

  const THRESHOLDS = {
    XS: 9,
    S: 49,
    M: 199,
    L: 499,
    XL: Infinity,
  };

  async function isGenerated(filename) {
    if (GENERATED.some((p) => p.test(filename))) return true;
    if (filename.endsWith(".java")) {
      try {
        const resp = await fetch(
          `https://raw.githubusercontent.com/${owner}/${repo}/${sha}/${filename}`,
          { headers: { Range: "bytes=0-255", Authorization: `token ${token}` } }
        );
        if (resp.ok) {
          const text = await resp.text();
          if (text.includes("Generated by the protocol buffer compiler")) return true;
        }
      } catch (e) {
        console.warn(filename, e.message);
      }
    }
    return false;
  }

  function getSize(total) {
    return Object.entries(THRESHOLDS).find(([, max]) => total <= max)[0];
  }

  async function calculateSize() {
    let total = 0;
    const maxThreshold = Math.max(...Object.values(THRESHOLDS).filter(isFinite));
    for (let page = 1; ; page++) {
      const files = await github.rest.pulls.listFiles({
        owner,
        repo,
        pull_number: pr,
        per_page: 100,
        page,
      });
      const done = files.data.length < 100;
      for (const f of files.data) {
        if (!(await isGenerated(f.filename))) {
          total += f.additions + f.deletions;
        }
      }
      if (done || total > maxThreshold) break;
    }
    return getSize(total);
  }

  async function ensureLabelExists(labelName) {
    try {
      await github.rest.issues.getLabel({
        owner,
        repo,
        name: labelName,
      });
      console.log(`Label ${labelName} exists`);
    } catch (error) {
      if (error.status === 404) {
        console.log(`Label ${labelName} does not exist, creating it`);
        await github.rest.issues.createLabel({
          owner,
          repo,
          name: labelName,
          color: "ededed",
        });
        console.log(`Label ${labelName} created`);
      } else {
        throw error;
      }
    }
  }

  const size = await calculateSize();
  const sizeLabel = `size/${size}`;
  console.log(`Calculated size label: ${sizeLabel}`);

  // Get existing labels on the PR
  const existingLabels = await github.rest.issues.listLabelsOnIssue({
    owner,
    repo,
    issue_number: pr,
  });
  const existingLabelNames = existingLabels.data.map(({ name }) => name);
  console.log("Existing labels:", existingLabelNames);

  // Remove old size/* labels (except the current one)
  const labelsToRemove = existingLabelNames.filter(
    (name) => name.startsWith("size/") && name !== sizeLabel
  );
  console.log("Labels to remove:", labelsToRemove);
  if (labelsToRemove.length > 0) {
    const results = await Promise.allSettled(
      labelsToRemove.map((name) =>
        github.rest.issues
          .removeLabel({
            owner,
            repo,
            issue_number: pr,
            name,
          })
          .catch((error) => {
            // Gracefully handle if label doesn't exist
            if (error.status === 404) {
              console.log(`Label ${name} already removed or doesn't exist`);
            } else {
              throw error;
            }
          })
      )
    );
    for (const { status, reason } of results) {
      if (status === "rejected") {
        console.error(reason);
      }
    }
  }

  // Add the new size label if not already present
  if (!existingLabelNames.includes(sizeLabel)) {
    console.log(`Adding label: ${sizeLabel}`);
    await ensureLabelExists(sizeLabel);
    await github.rest.issues.addLabels({
      owner,
      repo,
      issue_number: pr,
      labels: [sizeLabel],
    });
    console.log(`Label ${sizeLabel} added`);
  } else {
    console.log(`Label ${sizeLabel} already exists on PR`);
  }
};
