name: Team review

on:
  pull_request_target:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  review:
    runs-on: ubuntu-slim
    if: github.event.label.name == 'team-review'
    timeout-minutes: 5
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .github/workflows

      - name: Select reviewers
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          retries: 3
          script: |
            const script = require('./.github/workflows/team-review.js');
            await script({ github, context });
