name: TypeScript SDK

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "dev/clint/**"
      - ".github/workflows/docs.yml"
      - ".github/workflows/preview-docs.yml"
      - "mlflow/server/js/**"
      - ".github/workflows/js.yml"
  push:
    branches:
      - master
      - branch-[0-9]+.[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  typescript-sdk:
    if: github.event_name != 'pull_request' || (github.event.pull_request.draft == false || github.event.pull_request.user.login == 'Copilot' && github.event.pull_request.user.type == 'Bot')
    permissions:
      contents: read
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # 22.22.2 has a regression where `npm install -g` fails
        # See: https://github.com/nodejs/node/issues/62425
        node-version: [20, 22.22.1, 24]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: libs/typescript
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/untracked
      - uses: ./.github/actions/setup-python # Required for running a tracking server
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: libs/typescript/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run format check
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run core tests
        run: npm run test:core

      - name: Run tests for integrations
        run: npm run test:integrations
